Django/ModelProject/ModelProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views
#大家好
urlpatterns = [
    path('',views.main),
    path('admin/', admin.site.urls),
    # path('myApps/',include('myApp.urls',namespace='app')),
    url(r'^myApp/',include('myApp.urls',namespace='app')),
]

Django/ModelProject/myApp/urls.py
from django.urls import path,include
from django.conf.urls import url
from .import views
app_name='myApp'
urlpatterns = [

    path('',views.index),
    path('news/',views.news),
    path('addStudent/',views.addStudent),
    path('addStudent2/', views.addStudent2),
    path('getStudents/',views.getStudents),
    path('students0/',views.students0),
    # path('stu/(\d+)',views.stupage),
    url(r'^stu/(\d+)/$',views.stupage),
    path('stusearch/',views.stuserach),
    url(r'^attributes/$',views.attributes),
    url(r'^get1/$',views.get1),
    url(r'^get2/$',views.get2),
    url(r'^regist/$',views.regist),
    url(r'^cookietest/$',views.cookietest),
    url(r'^redirect1/$',views.redirect1),
    url(r'^redirect2/$',views.redirect2),
    url(r'^me/$',views.me),
    url(r'^submit/$',views.submit),
    url(r'^main/$',views.main),
    url(r'^quit/$',views.quit),
    url(r'^s_list/$',views.s_list),
    url(r'^goods/(\d+)/$',views.good,name='good'),
    url(r'^qf/$',views.qf),
    url(r'^qf1/$',views.qf1),
    url(r'^verifycode/$',views.verifycode),
    url(r'^dl/$',views.dl),
    url(r'^dlcheck/$',views.dlcheck),
    url(r'^upfile/$',views.upfile),
    url(r'^savefile/$',views.savefile),
    url(r'^studentpage/(\d+)/$',views.studentpage),



]

Django/ModelProject/myApp/models.py
from django.db import models

# Create your models here.
class Grades(models.Model):
    gname = models.CharField(max_length=20)
    gdate = models.DateTimeField()
    ggirlnum = models.IntegerField()
    gboynum = models.IntegerField()
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.gname
    class Meta:
        db_table ="grades"
        ordering =["id"]
# 自定义模型管理器
class StudentManager(models.Manager):
    def get_querySet(self):
        return super(StudentManager,self).get_queryset().filter(isDelete=False)
    def createStudnet(self, name, age, gender, contend, grade, lastT, createT, isD=False):
        stu = self.model()
        # print(type(grade))
        stu.sname = name
        stu.sage = age
        stu.sgender = gender
        stu.scontend = contend
        stu.sgrade = grade
        stu.lastTime = lastT
        stu.createTime = createT
        return stu



class Student(models.Model):
    #自定义模型管理器
    stuObj = models.Manager()
    stuObj2 = StudentManager()
    #当自定义模型管理器，objects就不存在了
    sname = models.CharField(max_length=20)
    sgender = models.BooleanField(default=True)
    sage = models.CharField(max_length=20)
    scontend = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)
    #关联外键
    sgrade = models.ForeignKey("Grades",on_delete=models.CASCADE)
    def __str__(self):
        return self.sname
    lastTime = models.DateTimeField(auto_now=True)
    createTime = models.DateField(auto_now_add=True)
    class Meta:
        db_table ="students"
        ordering =["id"]#升序  -id降序
    @classmethod#类方法
    def createStudent(cls,name,age,gender,content,grade,lastT,createT,isDel=False):
        stu = cls(sname=name,sage=age,sgender=gender,scontend=content,sgrade= grade,lastTime=lastT,createTime=createT,isDelete=isDel)
        return stu

from tinymce.models import HTMLField
class Text(models.Model):
    str = HTMLField()



Django/ModelProject/myApp/views.py
from django.shortcuts import render
from .models import Student,Grades
import os

# import sys
# sys.path.append('M:\PythonWeb\Django\ModelProject\ModelProject')
# import settings
# Create your views here.
from django.http import HttpResponse

def index(request):
    # return HttpResponse("This is the mainpage of myApp!!!")
    username = request.session.get("name","游客")
    return render(request,'myApp/myAppindex.html',{'username':username})

def news(req):
    return HttpResponse("News News News!!!")

def addStudent(req):
    grade = Grades.objects.get(pk=1)
    stu = Student.createStudent("刘德华",34,True,"我叫刘德华",
                                grade,"2018-4-18","2018-4-16")
    stu.save()
    return HttpResponse("ADD OK!")
def addStudent2(request):
    grade = Grades.objects.get(pk=1)
    stu = Student.stuObj2.createStudnet("张学友",55,True,"我叫张学友，凯哥帅", grade, "2017-8-10", "2017-8-11")
    stu.save()
    return HttpResponse("*********")

def getStudents(req):
    s = Student.stuObj2.all().filter(sage=18).count()
    return HttpResponse(s)
def students0(req):
    s = Student.stuObj2.all()[0:2]
    return HttpResponse(s.values())
def stupage(req,page):
    page = int(page)
    if page <= 0:
        page = 1
    num1 = (page-1)
    num2 = page
    stu = Student.stuObj2.all()[num1*3:num2*3]
    return HttpResponse(stu.values())

def stuserach(req):
    # stulist = Student.stuObj2.filter(sage__exact=18)
    # stulist = Student.stuObj2.filter(sname__contains="刘")
    # stulist = Student.stuObj2.filter(sname__startswith="张")
    # stulist = Student.stuObj2.filter(sname__endswith="1")
    # stulist = Student.stuObj2.filter(sname__isnull=False)
    # stulist = Student.stuObj2.filter(pk__in=[1,4])
    # stulist = Student.stuObj2.filter(sage__lt=30)
    # stulist = Student.stuObj2.filter(createTime__year=2018)
    # stulist = Student.stuObj2.filter(sname__contains="刘%")
    #查找描述中含有刘德华三个字的学生属于哪个班级 123
    # grade = Grades.objects.filter(student__scontend__contains="刘德华")

    # from django.db.models import Max
    # stu_MaxAge = Student.stuObj2.aggregate(Max('sage'))
    from django.db.models import F,Q
    # grade = Grades.objects.filter(ggirlnum__gt=F('gboynum'))
    # s = Student.stuObj2.filter(Q(sage__gt=30) | Q(sage__lt=19))
    # s = Student.stuObj2.filter(Q(sage=34))
    s = Student.stuObj2.filter(~Q(sage__gt=34))
    return HttpResponse(s.values())

def attributes(req):
    print(req.path)
    print(req.method)
    print(req.encoding)
    print(req.GET)
    print(req.POST)
    print(req.FILES)
    print(req.COOKIES)
    print(req.session)
    return HttpResponse("OOOOO")
#http://127.0.0.1:8080/myApp/get1?a=565&b=%E5%88%98%E8%A1%8D%E8%81%AA
def get1(req):
    a = req.GET.get("a")
    b = req.GET.get("b")
    return HttpResponse("a = "+a+"  b = "+b)
#django2 中不允许通过GET传递多个相同拥有相同键的值，后面的键的值会覆盖前面的键的值
#djagn
def get2(req):
    a = req.GET.get("a")
    a1 = a[0]
    a2 = a[1]
    b = req.GET.get("b")
    return HttpResponse("a1 = "+a1+" a2 = "+a2+" b = "+b)

def regist(req):
    if req.method == "GET":
        return render(req,"myApp/regist.html")
    else:
        name = req.POST.get("name")
        age = req.POST.get("age")

        return HttpResponse("你好！！"+name+"  "+age)

def cookietest(req):
    res = HttpResponse()
    # cookie = req.COOKIES
    # res.set_cookie("lyc","good")
    # res.write("<h1>"++"</h1>")
    return res
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
def redirect1(req):
    return redirect("/myApp/redirect2")

def redirect2(req):
    return HttpResponse("<h1>我是重定向的页面</h1>")

def me(req):
    username = req.session.get("name",'游客')
    return render(req,'myApp/me.html',{'username':username})
def submit(req):
    username = req.POST.get("name")
    req.session['name'] = username#不设置两个星期后过期
    req.session.set_expiry(1000)#1000s之后过期
    return redirect('/myApp/main')
def main(req):
    username = req.session.get("name","游客")
    return HttpResponse("<h1>"+username+"</h1>")
from django.contrib.auth import logout
def quit(req):
    # req.session['name'] = None
    logout(req)
    req.session.clear()
    req.session.flush()
    return HttpResponse('<h1 style="color: red">您已经成功退出了。。</h1>')

def s_list(req):
    s_lists = Student.stuObj2.all()
    print(s_lists)
    return render(req,'myApp/s_list.html',{'s_list':s_lists,'num':10,'hh':'<h1>这是一个h1标签</h1>'})

def good(req,id):
    return render(req,'myApp/good.html',{'num':id})

def qf(req):
    return render(req,'myApp/base.html')
def qf1(req):
    return render(req,'myApp/base1.html')

def verifycode(request):
    #引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), random.randrange(20, 100))
    width = 100
    height = 50
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str = '1234567890QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str[random.randrange(0, len(str))]
    #构造字体对象
    font = ImageFont.truetype(r'D:\fonts\georgiai.ttf', 40)
    #构造字体颜色
    fontcolor1 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor2 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor3 = (255, random.randrange(0, 255), random.randrange(0, 255))
    fontcolor4 = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor1)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor2)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor3)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor4)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    # request.session['verifycode'] = rand_str
    #内存文件操作
    request.session['verify'] = rand_str
    import io
    buf = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

def dl(req):
    f = req.session.get('flag',True)
    s = ''
    if f == False:
        s = '，验证码输入有误，请重新输入'
    req.session['flag'] = True
    return render(req,'myApp/dl.html',{'flag':s})


def dlcheck(req):
    code1 = req.POST.get('verifycode').upper()
    code2 = req.session['verify'].upper()
    if code1 == code2:
        return HttpResponse("登录成功")
    else:
        req.session['flag'] = False
        return redirect('/myApp/dl')

def upfile(req):
    return render(req,'myApp/upfile.html')
from django.conf import settings
def savefile(req):
    if req.method == 'POST':
        f = req.FILES["img_file"]
        filepath = os.path.join(settings.MEDIA_ROOT,f.name)
        with open(filepath,'wb') as fw:
            for info in f.chunks():
                fw.write(info)
        return HttpResponse('上传成功')
    else:
        return HttpResponse('上传失败')
from .models import Student
from django.core.paginator import Paginator
def studentpage(req,pageid):
    alllist = Student.stuObj2.all()
    paginator = Paginator(alllist,2)
    page = paginator.page(pageid)
    for i in page:
        print(i.sname)
    return render(req,'myApp/student_list.html',{'student':page})






Django/ModelProject/templates/myApp/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>千峰互联</title>
{#		<script src="js/jquery-1.11.3.min.js" type="text/javascript" charset="utf-8"></script>#}
        <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>

        <link rel="stylesheet" type="text/css" href="static/css/css.css"/>

	</head>
	<body>
		<div class="container">

			<div class="top">
				<a href=""><img src="static/img/2.png" class="top_img"/></a>
				<ul>
				<li><a href="">首页</a></li>
				<li><a href="">走进千峰</a></li>
				<li><a href="">人才服务</a></li>
				<li><a href="">千峰教育</a></li>
				<li><a href="">好程序员</a></li>
				<li><a href="">扣丁学堂</a></li>
				<li><a href="">APP研发</a></li>
				<li><a href="">培训服务</a></li>
				<li><a href="">创业孵化</a></li>
			</ul>
			</div>
			<img src="static/img/1.png" class="banner"/>
		</div>
        {% block main %}


        {% endblock main %}

		<div class="container introduce">
			<div class="middle">
				<ul>
					<li>
						<a href="">
							<img src="img/7.png"/>
							<p>千峰教育</p>
							<p>国内最大的移动互联网开发人才提供平台</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
						</a>
					</li>
					<li>
						<a href="">
							<img src="img/11.png"/>
							<p>千峰教育</p>
							<p>国内最大的移动互联网开发人才提供平台</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
						</a>
					</li>
					<li>
						<a href="">
							<img src="img/10.png"/>
							<p>千峰教育</p>
							<p>国内最大的移动互联网开发人才提供平台</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
						</a>
					</li>
					<li>
						<a href="">
							<img src="img/9.png"/>
							<p>千峰教育</p>
							<p>国内最大的移动互联网开发人才提供平台</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
							<p>精准高效的人才匹配</p>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="news">
			<a href=""><img src="img/3.png" class="news_image"/></a>
			<div class="new_m">
			<a href="" class="news_var">
				<span>动态新闻</span>
				<span>千峰公开课IOS开篇之战 性感约会IOS 7</span>
				<span>千峰公开课IOS开篇之战 性感约会IOS 7千峰公开课IOS开篇之战性感约会IOS 7千峰公开课IOS开篇之战 性感约会IOS 7</span>
			</a>
			<ul class="train">
				<li><a href="">&gt;企业内训首选千峰教育 高级讲师再赴沃尔玛倾</a></li>
				<li><a href="">&gt;企业内训首选千峰教育 高级讲师再赴沃尔玛倾</a></li>
				<li><a href="">&gt;企业内训首选千峰教育 高级讲师再赴沃尔玛倾</a></li>
				<li><a href="">&gt;企业内训首选千峰教育 高级讲师再赴沃尔玛倾</a></li>
			</ul>
			</div>

			<div class="new_end">
				<p>动态新闻</p>
				<p><a href=""><img src="img/6.png"/><span>点击咨询</span></a><a href=""><img src="img/6.png"/><span>点击咨询</span></a></p>
				<p>400-654-7778</p>
				<ul>
					<li>培训咨询：010-82790226/7</li>
					<li>培训咨询：010-82790226/7</li>
					<li>培训咨询：010-82790226/7</li>
					<li>培训咨询：010-82790226/7</li>
				</ul>
			</div>
		</div>
		<div class="foot">
			<div class="foot_message">
				<div>
					<ul>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
					</ul>
					<ul>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
					</ul>
					<ul>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
					</ul>
					<ul>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
					</ul>
					<ul>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
						<li><a href="">走进千峰</a></li>
					</ul>
				</div>
				<div>
					<img src="img/4.png"/>
				</div>
				<div>
					<img src="img/5.png"/>
				</div>
			</div>
		</div>
		<div class="footer">
			<p>Copyright 2007-2014 北京千峰互联网科技有限公司</p>
		</div>
	</body>
</html>

Django/ModelProject/templates/myApp/base1.html
{% extends "myApp/base.html" %}
{% block main %}
    <h1>我是个好人！！！</h1>
{% endblock main %}

Django/ModelProject/templates/myApp/dl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="/myApp/dlcheck/" method="post">
    {% csrf_token %}
    <input type="text" name="verifycode"/>
    <img src="/myApp/verifycode" alt="验证码">
    <input type="submit" value="登录">
    <span>{{ flag }}</span>
</form>



</body>
</html>

Django/ModelProject/templates/myApp/good.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>good</title>
</head>
<body>
<h1>GOOD:{{ num }}</h1>
</body>
</html>

Django/ModelProject/templates/myApp/me.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>我的登录页面</title>
</head>
<body>
<h1 style="color: mediumspringgreen">欢迎，{{username}}！！！</h1>
<form action="/myApp/submit/" method="post">
    {% csrf_token %}
    姓名：<input type="text" value="" name="name">
    <input type="submit">
</form>
<form action="/myApp/quit">
    <input type="submit" value="退出登录。。。">
</form>
</body>
</html>

Django/ModelProject/templates/myApp/myAppindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>myApp主页</title>
    
</head>
<body>
    <p style="color: mediumspringgreen">{{username}}好，我是myApp的主页大家好</p>
    <a href="me/">{{username}}</a>
</body>
</html>

Django/ModelProject/templates/myApp/regist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    姓名：<input type="text" name="name" value="">
    <hr>
    年龄：<input type="text" name="age" value="">

    <input type="submit" value="注册">
</form>
</body>
</html>

Django/ModelProject/templates/myApp/s_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生信息查询</title>
</head>
<body>
<a href="/myApp/goods/100/">硬连接</a>
<a href="{% url 'app:good' 100%}">反向代理</a>

{% for i in s_list %}
    {% if forloop.counter|divisibleby:2 %}

        <span style="color: red">偶数行：</span>
    {% endif %}
    <h2>姓名：{{ i.sname }}</h2>
    <h2>年龄：{{ i.sage }}</h2>
    {% if i.gender != 0 %}
        <h2>性别：男</h2>
        {% else %}
        <h2>性别：女</h2>
    {% endif %}
    <h2>描述：{{ i.scontent }}</h2>
    <hr>
    {% empty %}
    <h2>数据库中没有数据了</h2>
{% endfor %}
<h1>{{ s_list|join:'&'}}</h1>
{# 注释：当这个值h1没有被传递进来，或者h1的值为FALSE，则填充default的值#}
<h1>{{ h1|default:'没有'}}</h1>
<h1>{{ num|add:-6 }}</h1>
<h1>num/(1*5)= {% widthratio num 1 5 %}</h1>
<h1>num/(10*1)= {% widthratio num 10 1 %}</h1>
{% comment %}
    这是多行注释
{% endcomment %}
{{ hh }}
{{ hh|safe }}
{% autoescape off %}
{{ hh }}
{{ hh }}
{% endautoescape %}
</body>
</html>

Django/ModelProject/templates/myApp/student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生列表</title>
</head>
<body>
<ul>
    {% for stu in student %}
    <li>
        {{ stu.sname}}--{{stu.sgrade }}
    </li>
    {% endfor %}
</ul>
<ul>
    {% for index in student.paginator.page_range %}
        {% if index == student.number %}
            <li style="display: inline-block">
                <a href="/myApp/studentpage/{{ index }}" style="color: gold">{{ index }}</a>
            </li>
        {% else %}
            <li style="display: inline-block">
                <a href="/myApp/studentpage/{{ index }}">{{ index }}</a>
            </li>
        {% endif %}

    {% endfor %}
</ul>

</body>
</html>

Django/ModelProject/templates/myApp/upfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传头像</title>
</head>
<body>
<form action="/myApp/savefile/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="img_file">
    <input type="submit" value="上传">
</form>

</body>
</html>